Qa capstone PR
gdvl777/capstone pull request #1
Opened 2023-03-25 22:16 UTC by gdvl777

Project requirements
You should personalize the content of your page. Choose a topic that is different than the one in the original design.

You should follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including:

Colors.
Typography: font face, size and weight (we suggest using [Lato](https://www.latofonts.com/) as it is a free font similar to the one used in the original design).
Layout: composition and space between elements.
The pages should look almost identical to the original design. Small adjustments like text or image changes are acceptable.

You can use a CSS framework (for example Bootstrap) for styling, if you want to.

You should build only these 2 pages:

The home page.
The about page.
Each of these pages should have versions for 2 different screen sizes:

Mobile: up to 768px wide.
Desktop: 768px or wider.
Interactions

Links
The home page should have a link in the menu to the about page.
The logo in the header links to the home page.

Mobile menu
When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
There are no guidelines for the mobile menu in the docs, but you should implement it so it is consistent with the design (colors, typography, spacings, etc.).
The mobile menu should have a close (X) button that closes the menu.
Dynamic page

The section "Featured speakers" should be created dynamically in JavaScript.
You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.
Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07).

The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

2023-03-25 22:29 UTC, jerryowusu reviewed
Hi @gdvl777 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a pull request with most linters tests failing. Kindly ensure that all the linters shows green (passed) before submitting for another review. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-25 23:51 UTC, gdvl777 reviewed
Everything ok! Good job so far

2023-03-25 23:54 UTC, gdvl777 commented
Everything ok

2023-03-26 00:50 UTC, Owusu-Desmond requested changes
Hi @gdvl777 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-26 00:50 UTC, Owusu-Desmond commented on index.html
> +
- [ ] From the project requirements, you should stick to [Cindy's design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), But as you can see, your nav padding, your background design, text style, and alignment of elements do not match [Cindy's design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). So please make sure that you adjust the style of your design to match **_exactly_** like Cindy's design :+1: 

### Your Design on desktop
![image](https://user-images.githubusercontent.com/92303891/227747494-4d38b450-4693-4c9c-9ab0-8a7d0b3b4e38.png)

### Cindy Design on desktop
![image](https://user-images.githubusercontent.com/92303891/227749053-6683e4fc-1eb6-4518-b428-1be0d30c9f9b.png)

### Your Design on mobile
![image](https://user-images.githubusercontent.com/92303891/227748992-0039309d-1b03-42c2-ab96-79da095aab96.png)

### Cindy's design on mobile
![image](https://user-images.githubusercontent.com/92303891/227749016-5eb6ad7c-7bd9-450a-ab95-98a12f086176.png)

2023-03-26 00:50 UTC, Owusu-Desmond commented on index.html
> +
- [ ] From the project requirements, you should stick to [Cindy's design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), But as you can see, your `SUITES` section suppose to have 5 categories of containers, your images are not showing, you are missing the `SEE THE WHOLE PROGRAM` text and you have no background design which makes your design not matching [Cindy's design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). So please make sure that you adjust the style of your design to match **_exactly_** like Cindy's design :+1: 

### Your design
![image](https://user-images.githubusercontent.com/92303891/227747868-399a343f-1ec6-47cb-8377-994aadc96d43.png)

### Cindy's design
![Screenshot from 2023-03-25 23-58-15](https://user-images.githubusercontent.com/92303891/227748403-3bcf03b9-1880-414a-9976-d2f5b2025a4c.png)

2023-03-26 00:50 UTC, Owusu-Desmond commented on index.html
> +      <div class="grid-container">
- [ ] From the project requirements, you should stick to [Cindy's design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), But as you can see, in your top players section your images are not showing and your margin and text style does not match [Cindy's design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). So please make sure that you adjust the style of your design to match **_exactly_** like Cindy's design :+1: 

### Your design
![image](https://user-images.githubusercontent.com/92303891/227748521-13c7965a-0093-4cc8-b6a6-6c4b2aa0d3dd.png)


### Cindy's design
![Screenshot from 2023-03-26 00-07-44](https://user-images.githubusercontent.com/92303891/227748375-89932e9b-bc55-4e4a-ba99-b50f8939a825.png)

2023-03-26 00:50 UTC, Owusu-Desmond commented on about.html
> +            Men's and Women's Singles will feature 64 players each in the Main Draw. 50 players will be automatically entered based on ITTF World Table Tennis Ranking. <br>
- [ ] From the project requirements, you should stick to [Cindy's design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), But as you can see, your nav padding, your background design, text style, and alignment of elements do not match [Cindy's design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). So please make sure that you adjust the style of your design to match **_exactly_** like Cindy's design :+1: 
  
  ### Your Design
  ![image](https://user-images.githubusercontent.com/92303891/227748590-112b877a-f22c-4a1c-a81b-d1caae24af1d.png)
  
  ### Cindy's design
  ![image](https://user-images.githubusercontent.com/92303891/227748640-7dd1a7fb-80b2-4c11-94b0-afdc81999e90.png)

2023-03-26 00:50 UTC, Owusu-Desmond commented on about.html
> +
- [ ] From the project requirements, you should stick to [Cindy's design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), But as you can see, the blurred images, logo are not showing which makes your project design not matching [Cindy's design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). So please make sure that you adjust the style of your design to match **_exactly_** like Cindy's design :+1: 

### Your Design
![image](https://user-images.githubusercontent.com/92303891/227748837-676fe509-7118-4e84-b1ad-0f251b6fec97.png)


### Cindy's design
![image](https://user-images.githubusercontent.com/92303891/227748815-19cf08a6-b8c7-44f5-bab5-2b7031841bb7.png)

2023-03-26 00:50 UTC, Owusu-Desmond commented on README.md
> +- This is the [Loom Walktrough Video](https://www.loom.com/share/1f689459a7134b71846c7d1c1bd3d778) of my project.
- [ ] Please this recorded video is not a video of your project so make sure that you record a video of this project as it is required in the project requirement. :warning:

2023-03-26 00:50 UTC, Owusu-Desmond commented on README.md
> +
- [ ] Hey this live demo link is not your project so make sure that you replace it with your project live demo link :warning:

2023-03-27 14:23 UTC, closed without merging